import argparse
import os
import select
import shlex
import shutil
import subprocess
import sys
import sysconfig
from importlib import metadata
from pathlib import Path
from urllib import error, request
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from geosql.installation_id import get_installation_id
from geosql.paths import references_dir_path, skill_file_path

PACKAGE_ROOT = Path(__file__).resolve().parent
ROOT_SKILL_FILE = skill_file_path()
ROOT_REFERENCES_DIR = references_dir_path()
DEFAULT_VERSION_CHECK_URL = "https://cloud.dekart.xyz/api/v1/version/geosql"
DEKART_LAUNCHER_MARKER = "Generated by GeoSQL for an isolated Dekart CLI"
AGENT_LABELS = {
    "claude": "Claude Code",
    "codex": "Codex",
    "copilot": "GitHub Copilot",
    "opencode": "OpenCode",
    "vibe": "Mistral Vibe",
    "all": "your selected agents",
}


def build_parser():
    """Build CLI parser for geosql commands."""
    parser = argparse.ArgumentParser(
        prog="geosql",
        description="Install GeoSQL files into local AI toolchains.",
    )
    subparsers = parser.add_subparsers(dest="command")

    install = subparsers.add_parser("install", help="Install geosql into a supported CLI.")
    install.add_argument("target", choices=["claude", "codex", "copilot", "opencode", "vibe", "all"], help="CLI target to install geosql into.")

    return parser


def telemetry_disabled():
    """Return True if telemetry/version ping is disabled by env."""
    # Canonical opt-out is DO_NOT_TRACK=1 (or true/yes/on).
    # DNT=1 is supported for compatibility with common tooling.
    for key in ("DO_NOT_TRACK", "DNT"):
        value = os.environ.get(key, "").strip().lower()
        if value in {"1", "true", "yes", "on"}:
            return True
    return False


def get_installed_version():
    """Return installed package version or 'unknown'."""
    try:
        return metadata.version("geosql")
    except metadata.PackageNotFoundError:
        return "unknown"
    except Exception:
        return "unknown"


def send_version_ping():
    """Send non-blocking CLI version ping to Dekart endpoint."""
    if telemetry_disabled():
        return
    url = os.environ.get("GEOSQL_VERSION_CHECK_URL", DEFAULT_VERSION_CHECK_URL).strip() or DEFAULT_VERSION_CHECK_URL
    try:
        installation_id = get_installation_id()
        url_parts = urlsplit(url)
        query = parse_qsl(url_parts.query, keep_blank_values=True)
        query.append(("installation_id", installation_id))
        url = urlunsplit((url_parts.scheme, url_parts.netloc, url_parts.path, urlencode(query), url_parts.fragment))
    except Exception:
        # Identity persistence is best effort and must not block the version check.
        pass
    version = get_installed_version()
    req = request.Request(url=url, method="GET")
    req.add_header("User-Agent", f"geosql/{version}")
    try:
        with request.urlopen(req, timeout=2):
            return
    except (error.URLError, TimeoutError, ValueError):
        return
    except Exception:
        return


def is_interactive_terminal():
    """Return True when stdin/stdout are interactive terminals."""
    return bool(sys.stdin.isatty() and sys.stdout.isatty())


def supports_ansi_colors():
    """Return True when terminal likely supports ANSI colors."""
    if not sys.stdout.isatty():
        return False
    if os.environ.get("NO_COLOR"):
        return False
    term = os.environ.get("TERM", "").strip().lower()
    return term not in {"", "dumb"}


def ansi_rgb(text, red, green, blue, bold=False):
    """Wrap text with ANSI 24-bit color if available."""
    if not supports_ansi_colors():
        return text
    style = "1;" if bold else ""
    return f"\033[{style}38;2;{red};{green};{blue}m{text}\033[0m"


def print_banner():
    """Print GeoSQL startup banner."""
    lines = [
        "  ____            ____   ___  _     ",
        " / ___| ___  ___ / ___| / _ \\| |    ",
        "| |  _ / _ \\/ _ \\\\___ \\| | | | |    ",
        "| |_| |  __/ (_) |___) | |_| | |___ ",
        " \\____|\\___|\\___/|____/ \\__\\_\\_____|",
    ]
    title_color = (140, 210, 245)
    for line in lines:
        print(ansi_rgb(line, title_color[0], title_color[1], title_color[2], bold=True))
    version = get_installed_version()
    print(ansi_rgb(f"GeoSQL installer v{version}", 235, 235, 235, bold=True))
    print()


def read_menu_key():
    """Read one key press for interactive menu selection."""
    if os.name == "nt":
        import msvcrt

        ch = msvcrt.getwch()
        if ch == "\x03":
            raise KeyboardInterrupt
        if ch == "\x1b":
            return "cancel"
        if ch in {"\r", "\n"}:
            return "enter"
        if ch in {"\x00", "\xe0"}:
            ch2 = msvcrt.getwch()
            if ch2 == "H":
                return "up"
            if ch2 == "P":
                return "down"
            return ""
        if ch in {"k", "K"}:
            return "up"
        if ch in {"j", "J"}:
            return "down"
        return ""

    import termios
    import tty

    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        ch = os.read(fd, 1)
        if ch == b"\x03":
            raise KeyboardInterrupt
        if ch in {b"\r", b"\n"}:
            return "enter"
        if ch in {b"k", b"K"}:
            return "up"
        if ch in {b"j", b"J"}:
            return "down"
        if ch == b"\x1b":
            ready, _, _ = select.select([sys.stdin], [], [], 0.03)
            if not ready:
                return "cancel"
            seq = os.read(fd, 2)
            if seq == b"[A":
                return "up"
            if seq == b"[B":
                return "down"
            return ""
        return ""
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)


def select_menu_option(title, options, default_index=0):
    """Render arrow-key menu and return selected index."""
    if not is_interactive_terminal() or not supports_ansi_colors() or not options:
        return None
    selected = max(0, min(int(default_index), len(options) - 1))
    cancelled = False

    def format_line(index):
        prefix = ">" if index == selected else " "
        line = f"  {prefix} {options[index]}"
        if index == selected:
            return ansi_rgb(line, 112, 181, 208, bold=True)
        return line

    try:
        print(ansi_rgb(title, 112, 181, 208, bold=True))
        print("Use ↑/↓ (or j/k) and Enter.")
        print()
        for idx in range(len(options)):
            print(format_line(idx))
        sys.stdout.write("\033[?25l")
        sys.stdout.flush()
        while True:
            key = read_menu_key()
            previous = selected
            if key == "up":
                selected = (selected - 1) % len(options)
            elif key == "down":
                selected = (selected + 1) % len(options)
            elif key == "enter":
                break
            elif key == "cancel":
                cancelled = True
                break

            if selected != previous:
                sys.stdout.write(f"\033[{len(options)}F")
                for idx in range(len(options)):
                    sys.stdout.write("\033[2K\r" + format_line(idx) + "\n")
                sys.stdout.flush()
    finally:
        sys.stdout.write("\033[?25h")
        sys.stdout.flush()
    print()
    if cancelled:
        return "cancel"
    return selected


def dekart_install_command():
    """Return the pip command for the current GeoSQL Python environment."""
    return [sys.executable, "-m", "pip", "install", "dekart"]


def print_dekart_commands(include_install):
    """Print repeatable commands for completing Dekart setup later."""
    print("You can set up Dekart later with:")
    if include_install:
        print(f"  {sys.executable} -m pip install dekart")
    print("  dekart init")


def current_python_dekart_cli():
    """Return the expected Dekart entry point in GeoSQL's Python environment."""
    executable = "dekart.exe" if os.name == "nt" else "dekart"
    return Path(sysconfig.get_path("scripts")) / executable


def find_environment_dekart_cli():
    """Return Dekart when installed inside GeoSQL's Python environment."""
    environment_cli = current_python_dekart_cli()
    return str(environment_cli) if environment_cli.is_file() else None


def find_dekart_cli():
    """Return Dekart only when agents can invoke it through PATH."""
    return shutil.which("dekart")


def expose_dekart_cli(dekart_path):
    """Expose an isolated Dekart entry point beside the reachable GeoSQL command."""
    geosql_path = shutil.which("geosql")
    if not geosql_path:
        return None
    launcher_dir = Path(geosql_path).parent
    if os.name == "nt":
        launcher = launcher_dir / "dekart.cmd"
        if launcher.exists():
            try:
                existing = launcher.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                return None
            if DEKART_LAUNCHER_MARKER not in existing:
                return None
        content = (
            f"@rem {DEKART_LAUNCHER_MARKER}\r\n"
            f'@if not exist "{dekart_path}" (\r\n'
            '@  del "%~f0"\r\n'
            "@  echo Dekart is no longer installed. Re-run geosql to set it up. 1>&2\r\n"
            "@  exit /b 127\r\n"
            ")\r\n"
            f'@"{dekart_path}" %*\r\n'
        )
        try:
            launcher.write_text(content, encoding="utf-8")
        except OSError:
            return None
    else:
        launcher = launcher_dir / "dekart"
        if launcher.is_symlink():
            return None
        if launcher.exists():
            try:
                existing = launcher.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                return None
            if DEKART_LAUNCHER_MARKER not in existing:
                return None
        quoted_target = shlex.quote(str(dekart_path))
        content = (
            "#!/bin/sh\n"
            f"# {DEKART_LAUNCHER_MARKER}\n"
            f"target={quoted_target}\n"
            'if [ ! -x "$target" ]; then\n'
            '  rm -f -- "$0"\n'
            '  echo "Dekart is no longer installed. Re-run geosql to set it up." >&2\n'
            "  exit 127\n"
            "fi\n"
            'exec "$target" "$@"\n'
        )
        try:
            launcher.write_text(content, encoding="utf-8")
            launcher.chmod(0o755)
        except OSError:
            return None
    return shutil.which("dekart")


def is_dekart_ready(dekart_path, timeout=10):
    """Return True when the installed Dekart CLI can reach its configured tools."""
    try:
        result = subprocess.run(
            [dekart_path, "tools", "--json"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
            timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0


def select_optional_dekart_action(title, options):
    """Ask an optional Dekart question, defaulting to the recommended setup."""
    if not is_interactive_terminal():
        return False

    try:
        choice = select_menu_option(title, options, default_index=0)
        if choice == "cancel":
            return False
        if choice is None:
            print(title)
            for index, label in enumerate(options, start=1):
                print(f"  {index}) {label}")
            while True:
                raw = input(f"Select [1-{len(options)}] (default: 1): ").strip()
                if "\x1b" in raw:
                    return False
                if not raw:
                    choice = 0
                    break
                if raw.isdigit() and 1 <= int(raw) <= len(options):
                    choice = int(raw) - 1
                    break
                print(f"Enter a number from 1 to {len(options)}, or press Escape to cancel.")
        return int(choice) == 0
    except (EOFError, KeyboardInterrupt):
        print()
        return False


def run_dekart_command(command):
    """Run a user-approved Dekart setup command attached to the terminal."""
    try:
        return subprocess.run(command, check=False).returncode
    except KeyboardInterrupt:
        print("\nDekart setup cancelled.", file=sys.stderr)
        return 130
    except OSError as exc:
        print(f"Could not run {' '.join(command)}: {exc}", file=sys.stderr)
        return 1


def offer_dekart_setup(agent_label="your agent"):
    """Check Dekart readiness and offer only the setup action still needed."""
    dekart_path = find_dekart_cli()
    interactive = is_interactive_terminal()
    if dekart_path and is_dekart_ready(dekart_path, timeout=10 if interactive else 2):
        print("GeoSQL and Dekart are ready.")
        return 0
    if dekart_path:
        dekart_path = find_dekart_cli()
    environment_dekart_path = None if dekart_path else find_environment_dekart_cli()

    cli_missing = dekart_path is None and environment_dekart_path is None
    cli_needs_exposure = dekart_path is None and environment_dekart_path is not None
    print()
    if cli_missing:
        print(f"Dekart CLI lets {agent_label} create maps and inspect results.")
        print("GeoSQL will run only after you confirm.")
        print(f"If needed, GeoSQL will expose the dekart command to {agent_label}.")
        print("Commands to run:")
        print(f"  {sys.executable} -m pip install dekart")
        print("  dekart init")
        title = "GeoSQL needs the Dekart CLI to render maps and connect\nyour warehouse."
        options = ["Install Dekart CLI (recommended, 4x correctness on GIS tasks)", "Install later"]
    elif cli_needs_exposure:
        print(f"Dekart CLI is installed but not available to {agent_label} yet.")
        print("GeoSQL can expose it, then run:")
        print(f"  {environment_dekart_path} init")
        title = "GeoSQL is using Dekart for Map-in-the-loop workflow"
        options = [f"Make Dekart CLI available to {agent_label} and set it up (recommended)", "Not Now"]
    else:
        print("The Dekart CLI is installed but is not ready yet.")
        print("Command to run:")
        print("  dekart init")
        title = "GeoSQL is using Dekart for Map-in-the-loop workflow"
        options = [f"Set up Dekart CLI for {agent_label} to create maps (recommended)", "Not Now"]

    if not interactive:
        print("Non-interactive terminal detected; GeoSQL did not change your Dekart setup.")
        if cli_needs_exposure:
            print(f"Add this directory to PATH, then run dekart init: {Path(environment_dekart_path).parent}")
        else:
            print_dekart_commands(include_install=cli_missing)
        return 0

    if not select_optional_dekart_action(title, options):
        print("GeoSQL is installed. Dekart setup was skipped.")
        if cli_needs_exposure:
            print(f"Add this directory to PATH, then run dekart init: {Path(environment_dekart_path).parent}")
        else:
            print_dekart_commands(include_install=cli_missing)
        return 0

    if cli_missing:
        install_command = dekart_install_command()
        install_code = run_dekart_command(install_command)
        if install_code == 130:
            print("GeoSQL is installed. Dekart CLI installation was cancelled.")
            print_dekart_commands(include_install=True)
            return 0
        if install_code != 0:
            print("Dekart CLI installation failed.", file=sys.stderr)
            print_dekart_commands(include_install=True)
            return install_code
        dekart_path = find_dekart_cli()
        if not dekart_path:
            environment_dekart_path = find_environment_dekart_cli()

    if not dekart_path and environment_dekart_path:
        dekart_path = expose_dekart_cli(environment_dekart_path)
        if dekart_path:
            print(f"Made Dekart available at {dekart_path}")

    if not dekart_path:
        expected_path = current_python_dekart_cli()
        print("Dekart is installed, but GeoSQL could not expose its command on PATH.", file=sys.stderr)
        print(f"Add this directory to PATH: {expected_path.parent}", file=sys.stderr)
        print_dekart_commands(include_install=cli_missing)
        return 1

    init_code = run_dekart_command([dekart_path, "init"])
    if init_code == 130:
        print("GeoSQL is installed. Dekart setup was cancelled.")
        print_dekart_commands(include_install=False)
        return 0
    if init_code != 0:
        print("Dekart setup did not finish.", file=sys.stderr)
        print_dekart_commands(include_install=False)
        return init_code

    if is_dekart_ready(dekart_path):
        print("GeoSQL and Dekart are ready.")
        return 0

    print("Dekart init finished, but Dekart is not ready yet.", file=sys.stderr)
    print("Check the connection with:")
    print("  dekart tools --json")
    print_dekart_commands(include_install=False)
    return 1


def install_skill_at(skill_dir, label):
    """Install geosql SKILL.md and references into a target skill directory."""
    skill_dir.mkdir(parents=True, exist_ok=True)

    skill_file = skill_dir / "SKILL.md"
    if not ROOT_SKILL_FILE.exists():
        print(f"Missing skill source: {ROOT_SKILL_FILE}", file=sys.stderr)
        return 1

    skill_source = ROOT_SKILL_FILE.read_text(encoding="utf-8")
    skill_file.write_text(skill_source, encoding="utf-8")
    installed_references = 0

    if ROOT_REFERENCES_DIR.exists() and ROOT_REFERENCES_DIR.is_dir():
        target_references_dir = skill_dir / "references"
        if target_references_dir.exists():
            shutil.rmtree(target_references_dir)
        shutil.copytree(ROOT_REFERENCES_DIR, target_references_dir)
        installed_references = sum(1 for path in target_references_dir.rglob("*") if path.is_file())

    print(f"Installed {label} skill at {skill_file}")
    if installed_references:
        print(f"Installed references at {skill_dir / 'references'} ({installed_references} file(s))")
    return 0


def install_claude_skill():
    """Install geosql files into Claude skill directory."""
    return install_skill_at(Path.home() / ".claude" / "skills" / "geosql", "Claude")


def install_codex_skill():
    """Install geosql files into Codex skill directory."""
    return install_skill_at(Path.home() / ".codex" / "skills" / "geosql", "Codex")


def install_copilot_skill():
    """Install geosql files into GitHub Copilot skill directory."""
    return install_skill_at(Path.home() / ".copilot" / "skills" / "geosql", "GitHub Copilot")


def install_opencode_skill():
    """Install geosql files into OpenCode skill directory."""
    return install_skill_at(Path.home() / ".config" / "opencode" / "skills" / "geosql", "OpenCode")


def vibe_home_path():
    """Return the configured Mistral Vibe home directory."""
    configured_home = os.environ.get("VIBE_HOME", "").strip()
    if configured_home:
        return Path(configured_home).expanduser()
    return Path.home() / ".vibe"


def install_vibe_skill():
    """Install geosql files into Mistral Vibe skill directory."""
    return install_skill_at(vibe_home_path() / "skills" / "geosql", "Mistral Vibe")


def detect_installed_agents():
    """Detect available agents and return ordered list of target ids."""
    detected = []
    claude_present = shutil.which("claude") is not None or (Path.home() / ".claude").exists()
    codex_present = shutil.which("codex") is not None or (Path.home() / ".codex").exists()
    copilot_present = shutil.which("copilot") is not None or (Path.home() / ".copilot").exists()
    opencode_present = shutil.which("opencode") is not None or (Path.home() / ".config" / "opencode").exists()
    vibe_present = shutil.which("vibe") is not None or vibe_home_path().exists()
    if claude_present:
        detected.append("claude")
    if codex_present:
        detected.append("codex")
    if copilot_present:
        detected.append("copilot")
    if opencode_present:
        detected.append("opencode")
    if vibe_present:
        detected.append("vibe")
    return detected


def manual_install_hint():
    """Print manual install guidance when no known agent is detected."""
    vibe_skill_dir = vibe_home_path() / "skills" / "geosql"
    vibe_skill_display = str(vibe_skill_dir) if os.environ.get("VIBE_HOME", "").strip() else "~/.vibe/skills/geosql"
    print("No supported agents detected (Claude Code / Codex / GitHub Copilot / OpenCode / Mistral Vibe).")
    print("Manual install steps:")
    print(f"  1) Claude: copy {ROOT_SKILL_FILE} -> ~/.claude/skills/geosql/SKILL.md")
    print(f"     and {ROOT_REFERENCES_DIR} -> ~/.claude/skills/geosql/references/")
    print(f"  2) Codex:  copy {ROOT_SKILL_FILE} -> ~/.codex/skills/geosql/SKILL.md")
    print(f"     and {ROOT_REFERENCES_DIR} -> ~/.codex/skills/geosql/references/")
    print(f"  3) Copilot: copy {ROOT_SKILL_FILE} -> ~/.copilot/skills/geosql/SKILL.md")
    print(f"     and {ROOT_REFERENCES_DIR} -> ~/.copilot/skills/geosql/references/")
    print(f"  4) OpenCode: copy {ROOT_SKILL_FILE} -> ~/.config/opencode/skills/geosql/SKILL.md")
    print(f"     and {ROOT_REFERENCES_DIR} -> ~/.config/opencode/skills/geosql/references/")
    print(f"  5) Mistral Vibe: copy {ROOT_SKILL_FILE} -> {vibe_skill_display}/SKILL.md")
    print(f"     and {ROOT_REFERENCES_DIR} -> {vibe_skill_display}/references/")
    return 1


def run_interactive_install():
    """Run interactive default installer flow for plain `geosql`."""
    print_banner()
    detected = detect_installed_agents()
    if not detected:
        return manual_install_hint()

    labels = []
    targets = []
    if "claude" in detected:
        labels.append("Install for Claude Code")
        targets.append("claude")
    if "codex" in detected:
        labels.append("Install for Codex")
        targets.append("codex")
    if "copilot" in detected:
        labels.append("Install for GitHub Copilot")
        targets.append("copilot")
    if "opencode" in detected:
        labels.append("Install for OpenCode")
        targets.append("opencode")
    if "vibe" in detected:
        labels.append("Install for Mistral Vibe")
        targets.append("vibe")
    if len(detected) > 1:
        labels.append("Install for All detected")
        targets.append("all")

    if is_interactive_terminal():
        choice = select_menu_option("Confirm install target", labels, default_index=len(labels) - 1 if len(labels) > 1 else 0)
    else:
        choice = None

    if choice == "cancel":
        print("Install cancelled.")
        return 1

    if choice is None:
        print("Detected agents: " + ", ".join(detected))
        default_index = len(labels) - 1 if len(labels) > 1 else 0
        default_human = str(default_index + 1)
        for index, label in enumerate(labels, start=1):
            print(f"  {index}) {label}")
        raw = input(f"Select [1-{len(labels)}] (default: {default_human}): ").strip() if is_interactive_terminal() else ""
        if raw.isdigit() and 1 <= int(raw) <= len(labels):
            picked = int(raw) - 1
        else:
            picked = default_index
    else:
        picked = int(choice)

    selected_target = targets[picked]
    print(f"Installing target: {labels[picked]}")
    return handle_install_target(selected_target)


def handle_install_target(target):
    """Install for one target or all."""
    if target == "claude":
        code = install_claude_skill()
    elif target == "codex":
        code = install_codex_skill()
    elif target == "copilot":
        code = install_copilot_skill()
    elif target == "opencode":
        code = install_opencode_skill()
    elif target == "vibe":
        code = install_vibe_skill()
    elif target == "all":
        code = 0
        code = max(code, install_claude_skill())
        code = max(code, install_codex_skill())
        code = max(code, install_copilot_skill())
        code = max(code, install_opencode_skill())
        code = max(code, install_vibe_skill())
    else:
        print(f"Unsupported install target: {target}", file=sys.stderr)
        return 2

    if code != 0:
        return code
    return offer_dekart_setup(AGENT_LABELS[target])


def main():
    """CLI entrypoint."""
    send_version_ping()
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "install":
        raise SystemExit(handle_install_target(args.target))

    raise SystemExit(run_interactive_install())


if __name__ == "__main__":
    main()
